name: scrape teams

on:
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r scraping/requirements.txt

      - name: execute py script # run main.py
        run: python scraping/teams_scraper.py