name: Scrape teams

on:
  schedule:
    - cron: "* * * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r scraping/requirements.txt

    - name: Run Python script
      run: python scraping/teams_scraper.py
